[tool.poetry]
name = "PyClits"
version = "1.0.0"
description = ""
authors = ["ASB"]

[tool.poetry.dependencies]
python = ">=3.7"
scipy = ">=1.3"
numpy = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
